'use strict'

const {
  API_CRYPTO_CLIENT_UNIQUE_ID,
  API_CRYPTO_CLIENT_PUBLIC_KEY,
  API_CRYPTO_CLIENT_ENCRYPTED_PRIVATE_KEY
} = process.env

const REQUIRED_CONFIG = [
  'API_CRYPTO_CLIENT_UNIQUE_ID',
  'API_CRYPTO_CLIENT_PUBLIC_KEY',
  'API_CRYPTO_CLIENT_ENCRYPTED_PRIVATE_KEY'
]

REQUIRED_CONFIG.forEach(key => {
  if (!process.env[key]) {
    console.error('[Error] Missing Api Crypto Config:', key)
    return process.exit(1)
  }
})

const API_CRYPTO_CONFIG = {
  CLIENT_UNIQUE_ID: API_CRYPTO_CLIENT_UNIQUE_ID,
  CLIENT_PUBLIC_KEY: API_CRYPTO_CLIENT_PUBLIC_KEY,
  CLIENT_ENCRYPTED_PRIVATE_KEY: API_CRYPTO_CLIENT_ENCRYPTED_PRIVATE_KEY
}

export default API_CRYPTO_CONFIG
